table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # Accept established and related connections
        ct state established,related accept
    }

    chain output {
        type filter hook output priority filter; policy drop;

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 443 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 8888 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 5594 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 8080 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 22 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 445 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 5985 accept

        # Allow outgoing traffic to the migration appliance and platform
        tcp dport 902 accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }
}